config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :appellation_wineries

  resources :wine_cellars
  resources :my_wine_cellars do
    resources :wines
    resources :wineries
    resources :my_wineries
  end

  resources :my_wineries
  resources :stocks
  resources :wines
  resources :appellations
  resources :wineries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-macaveapp sticky-top navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand text-white" href="/"><strong>MaCave</strong></a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item m-2">
              <%= link_to "My Wine Cellars", my_wine_cellars_path %>
            </li>
            <li class="nav-item m-2">
              <%= link_to "Wineries", wineries_path %>
            </li>
            <li class="nav-item m-2">
              <%= link_to "Appellations", appellations_path %>
            </li>
            <li class="nav-item m-2">
              <%= link_to "Appellation Wineries", appellation_wineries_path %>
            </li>
         </ul>
      </div>

      <div class="d-flex flex-row align-items-center">
        <%if !user_signed_in? %>
          <a href="/users/sign_in" class="btn btn-outline-light mr-2 rounded-pill">Sign in</a>
        <%else %>
          <div class="btn-group">

            <a type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle fa-2x"></i>
          <%end%>
            </a>
            <div class="dropdown-menu dropdown-position">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item"%>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
      </div>
  </div>
</nav>