config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :appellation_wineries

  resources :wine_cellars
  resources :my_wine_cellars do
    resources :wines
    resources :wineries
    resources :my_wineries
  end

  resources :my_wineries
  resources :stocks
  resources :wines
  resources :appellations
  resources :wineries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/my_wine.rb
class MyWine < ApplicationRecord
  belongs_to :wine
  belongs_to :my_wine_cellar
end

app/controllers/my_wines_controller.rb
class MyWinesController < ApplicationController
  before_action :set_my_wine, only: %i[ show edit update destroy ]

  # GET /my_wines or /my_wines.json
  def index
    @my_wine_cellar = MyWineCellar.find(params[:my_wine_cellar_id])
    @my_wines = MyWine.where(my_wine_cellar_id: params[:my_wine_cellar_id])
  end

  # GET /my_wines/1 or /my_wines/1.json
  def show
    @my_wine_cellar = MyWineCellar.find(params[:my_wine_cellar_id])
  end

  # GET /my_wines/new
  def new
    @my_wine = MyWine.new
  end

  # GET /my_wines/1/edit
  def edit
    @my_wine_cellar = MyWineCellar.find(params[:my_wine_cellar_id])
  end

  # POST /my_wines or /my_wines.json
  def create
    @my_wine = MyWine.new(my_wine_params)
    @my_wine.my_wine_cellar = MyWineCellar.find(params[:my_wine_cellar_id])

    respond_to do |format|
      if @my_wine.save
        format.html { redirect_to my_wine_cellar_my_wines_url  , notice: "My wine was successfully created." }
        format.json { render :show, status: :created, location: @my_wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_wines/1 or /my_wines/1.json
  def update
    respond_to do |format|
      if @my_wine.update(my_wine_params)
        format.html { redirect_to @my_wine, notice: "My wine was successfully updated." }
        format.json { render :show, status: :ok, location: @my_wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_wines/1 or /my_wines/1.json
  def destroy
    @my_wine.destroy
    respond_to do |format|
      format.html { redirect_to my_wines_url, notice: "My wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_wine
      @my_wine = MyWine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_wine_params
      params.require(:my_wine).permit(:wine_id, :my_wine_cellar_id, :description)
    end
end

app/views/my_wines/_form.html.erb
<%= simple_form_for([ @my_wine_cellar, @my_wine ],method: :post, url: my_wine_cellar_my_wines_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :wine %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/my_wines/edit.html.erb
<h1>Editing My Wine</h1>

<%= render 'form', my_wine: @my_wine %>

<%= link_to 'Show', @my_wine %> |
<%= link_to 'Back', my_wines_path %>

app/views/my_wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Wines</h1>

<table>
  <thead>
    <tr>
      <th>Winery</th>
      <th>Wine</th>
      <th>Description</th>
      <th>Wine Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_wines.each do |my_wine| %>
      <tr>
        <td><%= my_wine.wine.appellation_winery.winery.name %></td>
        <td><%= my_wine.wine.name %></td>
        <td><%= my_wine.description %></td>
        <td><%= my_wine.wine.wine_type %></td>
        <td><%= link_to 'Show', my_wine_cellar_my_wine_path(@my_wine_cellar, my_wine) %></td>
        <td><%= link_to 'Edit', edit_my_wine_cellar_my_wine_path(@my_wine_cellar, my_wine) %></td>
        <td><%= link_to 'Destroy', my_wine_cellar_my_wine_path(@my_wine_cellar, my_wine), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Wine', new_my_wine_cellar_my_wine_path %>

app/views/my_wines/new.html.erb
<h1>New My Wine</h1>

<%= render 'form', my_wine: @my_wine %>

<%= link_to 'Back', my_wine_cellar_my_wines_path %>

app/views/my_wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine:</strong>
  <%= @my_wine.wine_id %>
</p>

<p>
  <strong>Wine cellar:</strong>
  <%= @my_wine.my_wine_cellar_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @my_wine.description %>
</p>

<%= link_to 'Edit', edit_my_wine_cellar_my_wine_path(@my_wine_cellar, @my_wine) %> |
<%= link_to 'Back', my_wine_cellar_my_wines_path(@my_wine_cellar) %>