config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :appellation_wineries

  resources :wine_cellars
  resources :my_wine_cellars do
    resources :wines
    resources :wineries
    resources :my_wineries
  end

  resources :my_wineries
  resources :stocks
  resources :wines
  resources :appellations
  resources :wineries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/my_wine_cellar.rb
class MyWineCellar < ApplicationRecord
  belongs_to :user
  belongs_to :wine_cellar
  has_many :my_wineries, dependent: :destroy
  has_many :stocks, dependent: :destroy

end

app/controllers/my_wine_cellars_controller.rb
class MyWineCellarsController < ApplicationController
  before_action :set_my_wine_cellar, only: %i[ show edit update destroy ]

  # GET /my_wine_cellars or /my_wine_cellars.json
  def index
    @my_wine_cellars = MyWineCellar.all
  end

  # GET /my_wine_cellars/1 or /my_wine_cellars/1.json
  def show
    @my_wineries = MyWinery.where(my_wine_cellar_id: params[:id])
    @wines = Wine.where(appellation_winery_id: params[:id])
    @stocks = Stock.where(my_wine_cellar_id: params[:id])
  end

  # GET /my_wine_cellars/new
  def new
    @my_wine_cellar = MyWineCellar.new
    @wine_cellars = WineCellar.all
  end

  # GET /my_wine_cellars/1/edit
  def edit
    @wine_cellar = @my_wine_cellar.wine_cellar
  end

  # POST /my_wine_cellars or /my_wine_cellars.json
  def create
    @wine_cellars = WineCellar.all
    @my_wine_cellar = current_user.my_wine_cellars.create(wine_cellar: WineCellar.all.find_by(token: params[:my_wine_cellar][:token]))

    respond_to do |format|
      if @my_wine_cellar.save
        format.html { redirect_to @my_wine_cellar, notice: "My wine cellar was successfully created." }
        format.json { render :show, status: :created, location: @my_wine_cellar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_wine_cellar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_wine_cellars/1 or /my_wine_cellars/1.json
  def update
    respond_to do |format|
      if @my_wine_cellar.update(my_wine_cellar_params)
        format.html { redirect_to @my_wine_cellar, notice: "My wine cellar was successfully updated." }
        format.json { render :show, status: :ok, location: @my_wine_cellar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_wine_cellar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_wine_cellars/1 or /my_wine_cellars/1.json
  def destroy
    @my_wine_cellar.destroy
    respond_to do |format|
      format.html { redirect_to my_wine_cellars_url, notice: "My wine cellar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_wine_cellar
      @my_wine_cellar = MyWineCellar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_wine_cellar_params
      params.require(:my_wine_cellar).permit(:user_id, :wine_cellar_id)
    end
end

app/views/my_wine_cellars/_edit_form.html.erb
<%= simple_form_for(@my_wine_cellar, @wine_cellar) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :name  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/my_wine_cellars/_form.html.erb
<%= simple_form_for(@my_wine_cellar) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :token, collection: @winecellars , input_html: { value: nil } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/my_wine_cellars/edit.html.erb
<h1>Editing My Wine Cellar</h1>

<%= render './wine_cellars/form', wine_cellar: @my_wine_cellar.wine_cellar %>

<%= link_to 'Show', @my_wine_cellar %> |
<%= link_to 'Back', my_wine_cellars_path %>

app/views/my_wine_cellars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Wine Cellars</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Wine cellar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_wine_cellars.each do |my_wine_cellar| %>
      <tr>
        <td><%= my_wine_cellar.user.first_name %></td>
        <td><%= my_wine_cellar.wine_cellar.name %></td>
        <td><%= link_to 'Show', my_wine_cellar %></td>
        <td><%= link_to 'Edit', edit_my_wine_cellar_path(my_wine_cellar) %></td>
        <td><%= link_to 'Destroy', my_wine_cellar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Add an existing wine cellar', new_my_wine_cellar_path %>
<%= link_to 'New wine cellar', new_wine_cellar_path %>

app/views/my_wine_cellars/new.html.erb
<h1>New My Wine Cellar</h1>

<%= render 'form', my_wine_cellar: @my_wine_cellar %>

<%= link_to 'Back', my_wine_cellars_path %>

app/views/my_wine_cellars/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @my_wine_cellar.wine_cellar.name %></h1>

<%= link_to 'Edit', edit_my_wine_cellar_path(@my_wine_cellar) %> |
<%= link_to 'Back', my_wine_cellars_path %> |
<%= link_to 'Add new', my_wine_cellar_wineries_path(@my_wine_cellar) %>

<% @my_wineries.each do |my_winery| %>
  <%= link_to my_wine_cellar_winery_path(@my_wine_cellar, my_winery.winery_id), class: "secondary-link text-decoration-none" do %>
    <div class="wine-card">
      <div class="d-flex justify-content-between">
        <div>
          <strong><%= my_winery.winery.name %></strong>
          <div>
          </div>
          <div class="mt-2 ml-3">
            <% my_winery.winery.appellations.each do |appellation|%>
              <p class="m-0"><i> <%= appellation.name %></i></p>
            <% end %>
          </div>
        </div>
        <div>
            <% @stocks_by_winery = @stocks.where(wine_id: my_winery.winery.wine.id) %>
            <% @stocks_by_year = @stocks_by_winery.group_by {|w| w.vintage}.transform_values { |vals| vals.sum { |val| val[:quantity] } }.sort %>

          <table>
            <thead>
              <tr>
                <%# @stocks_by_year.map do |vintage, stock|  %>
                  <th><%#= vintage %></th>
                <%# end %>
              </tr>
            </thead>
            <tbody>
              <tr>
               <%# @stocks_by_year.map do |vintage, stock|  %>
                  <td><%#= stock %></td>
                <%# end %>
              </tr>
            </tbody>
            </table>

        </div>
      </div>
    </div>
  <% end %>
<% end %>