config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :appellation_wineries

  resources :wine_cellars
  resources :my_wine_cellars do
    resources :wines
    resources :wineries
    resources :my_wineries
  end

  resources :my_wineries
  resources :stocks
  resources :wines
  resources :appellations
  resources :wineries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appellation.rb
class Appellation < ApplicationRecord
  has_many :appellation_wineries, dependent: :destroy
  has_many :wineries, through: :appellation_to_wineries
  has_many :wines, through: :appellation_wineries

  validates :name, presence: true
  validates :location, presence: true

end

app/controllers/appellations_controller.rb
class AppellationsController < ApplicationController
  before_action :set_appellation, only: %i[ show edit update destroy ]

  # GET /appellations or /appellations.json
  def index
    @appellations = Appellation.all
  end

  # GET /appellations/1 or /appellations/1.json
  def show
  end

  # GET /appellations/new
  def new
    @appellation = Appellation.new
  end

  # GET /appellations/1/edit
  def edit
  end

  # POST /appellations or /appellations.json
  def create
    @appellation = Appellation.new(appellation_params)

    respond_to do |format|
      if @appellation.save
        format.html { redirect_to @appellation, notice: "Appellation was successfully created." }
        format.json { render :show, status: :created, location: @appellation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appellation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appellations/1 or /appellations/1.json
  def update
    respond_to do |format|
      if @appellation.update(appellation_params)
        format.html { redirect_to @appellation, notice: "Appellation was successfully updated." }
        format.json { render :show, status: :ok, location: @appellation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appellation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appellations/1 or /appellations/1.json
  def destroy
    @appellation.destroy
    respond_to do |format|
      format.html { redirect_to appellations_url, notice: "Appellation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appellation
      @appellation = Appellation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appellation_params
      params.require(:appellation).permit(:name, :location)
    end
end

app/views/appellations/_form.html.erb
<div data-controller="autocomplete">
  <%= simple_form_for(@appellation) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :location, placeholder: "Location", label: false, input_html: { data: { target: 'autocomplete.input'} } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/appellations/edit.html.erb
<h1>Editing Appellation</h1>

<%= render 'form', appellation: @appellation %>

<%= link_to 'Show', @appellation %> |
<%= link_to 'Back', appellations_path %>

app/views/appellations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appellations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Winery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appellations.each do |appellation| %>
      <tr>
        <td><%= appellation.name %></td>
        <td><%= appellation.location %></td>
        <td><%= link_to 'Show', appellation %></td>
        <td><%= link_to 'Edit', edit_appellation_path(appellation) %></td>
        <td><%= link_to 'Destroy', appellation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appellation', new_appellation_path %>

app/views/appellations/new.html.erb
<h1>New Appellation</h1>

<%= render 'form', appellation: @appellation %>

<%= link_to 'Back', appellations_path %>

app/views/appellations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appellation.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @appellation.location %>
</p>

<%= link_to 'Edit', edit_appellation_path(@appellation) %> |
<%= link_to 'Back', appellations_path %>